Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  SERVER_NAME = "mamoulinS"
  SERVER_IP = "192.168.56.110"

  config.ssh.insert_key = false

  config.vm.define SERVER_NAME, primary: true do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "libvirt" do |lv|
      lv.memory = "2048"
      lv.cpus = 2
    end
    server.vm.provision "shell", path: "server_init.sh"

  end
end

