Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  SERVER_NAME = "mamoulinS"
  SERVER_IP = "192.168.56.110"

  config.ssh.insert_key = false

  config.vm.define SERVER_NAME, primary: true do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "libvirt" do |lv|
      lv.memory = "4096"
      lv.cpus = 4
      lv.video_vram = 16
      lv.nested = true
      lv.cpu_mode = 'host-passthrough'
    end

    #####

    server.vm.provision "file",
      source: "./confs/app-one/deployment.yaml",
      destination: "/home/vagrant/deployment-1.yaml"

    server.vm.provision "file",
      source: "./confs/app-one/service.yaml",
      destination: "/home/vagrant/service-1.yaml"

    #####

    server.vm.provision "file",
      source: "./confs/app-two/deployment.yaml",
      destination: "/home/vagrant/deployment-2.yaml"

    server.vm.provision "file",
      source: "./confs/app-two/service.yaml",
      destination: "/home/vagrant/service-2.yaml"

    #####
      

    server.vm.provision "file",
      source: "./confs/app-three/deployment.yaml",
      destination: "/home/vagrant/deployment-3.yaml"

    server.vm.provision "file",
      source: "./confs/app-three/service.yaml",
      destination: "/home/vagrant/service-3.yaml"

    #####

    server.vm.provision "file",
      source: "./confs/ingress.yaml",
      destination: "/home/vagrant/ingress.yaml"

    server.vm.provision "shell", path: "scripts/server_init.sh"
  end
end
