Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  SERVER_IP = "192.168.56.110"
  SERVER_NAME = "mamoulinS"
  WORKER_IP = "192.168.56.111"

  config.ssh.insert_key = false

  config.vm.define SERVER_NAME, primary: true do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "libvirt" do |lv|
      lv.memory = "2048"
      lv.cpus = 1
    end

    server.vm.provision "file",
      source: "../shared_vm_key.pub",
      destination: "/home/vagrant/.ssh/shared_vm_key.pub"

    server.vm.provision "shell", inline: <<-SHELL
      mkdir -p /home/vagrant/.ssh
      cat /home/vagrant/.ssh/shared_vm_key.pub >> /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/authorized_keys
    SHELL

    server.vm.provision "shell", path: "server.sh"
  end

  config.vm.define "mamoulinSW" do |worker|
    worker.vm.hostname = "mamoulinSW"
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provider "libvirt" do |lv|
      lv.memory = "512"
      lv.cpus = 1
    end

    worker.vm.provision "file", 
      source: "../shared_vm_key",
      destination: "/home/vagrant/.ssh/shared_vm_key"
 
    worker.vm.provision "shell", inline: <<-SHELL
      chown vagrant:vagrant /home/vagrant/.ssh/shared_vm_key
      chmod 600 /home/vagrant/.ssh/shared_vm_key
    SHELL

    worker.vm.provision "shell", path: "worker.sh", args: [SERVER_IP, SERVER_NAME]
  end
end
