Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  SERVER_NAME = "mamoulinS"
  SERVER_IP = "192.168.56.110"

  config.vm.define SERVER_NAME, primary: true do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
    end

    server.vm.provision "file",
      source: "./docker_install.sh",
      destination: "/home/vagrant/docker_install.sh"

    server.vm.provision "file",
      source: "./install_p3.sh",
      destination: "/home/vagrant/install_p3.sh"

    server.vm.provision "shell", path: "install_p3.sh"
    end
end
